version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:15.2-alpine
    env_file:
      - ./.env
    ports:
      - "5433:5433"

  api:
    build:
        context: .
        dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_started
    env_file:
        - ./.env
    volumes:
      - ./:/api/library_practice/
      - ./static/:/api/library_practice/static/
      - ./media/:/api/library_practice/media/
    ports:
        - "8000:8000"
