# Generated by Django 4.2 on 2023-04-25 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="borrow_date",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="borrowed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateTimeField(),
        ),
    ]
