# Generated by Django 4.2 on 2023-04-26 07:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0003_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 4, 26))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 4, 26))
                ]
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 4, 26))
                ]
            ),
        ),
    ]
